name: AML3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - rdkit
  - openpyxl
  - numpy
  - scikit-learn
  - pymc
  - seaborn
  - shap
  - matplotlib-venn
  - tensorflow